[package]
name = "tvix_wasm_api"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.4"
tvix-eval = { git = "https://github.com/Rucadi/tvix", package = "tvix-eval" }
